// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: weaver.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeaverService_ExecuteRun_FullMethodName  = "/texture.WeaverService/ExecuteRun"
	WeaverService_ValidateRun_FullMethodName = "/texture.WeaverService/ValidateRun"
	WeaverService_InferSchema_FullMethodName = "/texture.WeaverService/InferSchema"
	WeaverService_HealthCheck_FullMethodName = "/texture.WeaverService/HealthCheck"
)

// WeaverServiceClient is the client API for WeaverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Weaver service - ML computation engine
type WeaverServiceClient interface {
	// Execute an algorithm run
	ExecuteRun(ctx context.Context, in *ExecuteRunRequest, opts ...grpc.CallOption) (*ExecuteRunResponse, error)
	// Validate if a run can be executed
	ValidateRun(ctx context.Context, in *ValidateRunRequest, opts ...grpc.CallOption) (*ValidateRunResponse, error)
	// Infer schema from CSV data
	InferSchema(ctx context.Context, in *InferSchemaRequest, opts ...grpc.CallOption) (*InferSchemaResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type weaverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeaverServiceClient(cc grpc.ClientConnInterface) WeaverServiceClient {
	return &weaverServiceClient{cc}
}

func (c *weaverServiceClient) ExecuteRun(ctx context.Context, in *ExecuteRunRequest, opts ...grpc.CallOption) (*ExecuteRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteRunResponse)
	err := c.cc.Invoke(ctx, WeaverService_ExecuteRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weaverServiceClient) ValidateRun(ctx context.Context, in *ValidateRunRequest, opts ...grpc.CallOption) (*ValidateRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRunResponse)
	err := c.cc.Invoke(ctx, WeaverService_ValidateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weaverServiceClient) InferSchema(ctx context.Context, in *InferSchemaRequest, opts ...grpc.CallOption) (*InferSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferSchemaResponse)
	err := c.cc.Invoke(ctx, WeaverService_InferSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weaverServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, WeaverService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeaverServiceServer is the server API for WeaverService service.
// All implementations must embed UnimplementedWeaverServiceServer
// for forward compatibility.
//
// Weaver service - ML computation engine
type WeaverServiceServer interface {
	// Execute an algorithm run
	ExecuteRun(context.Context, *ExecuteRunRequest) (*ExecuteRunResponse, error)
	// Validate if a run can be executed
	ValidateRun(context.Context, *ValidateRunRequest) (*ValidateRunResponse, error)
	// Infer schema from CSV data
	InferSchema(context.Context, *InferSchemaRequest) (*InferSchemaResponse, error)
	// Health check
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedWeaverServiceServer()
}

// UnimplementedWeaverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeaverServiceServer struct{}

func (UnimplementedWeaverServiceServer) ExecuteRun(context.Context, *ExecuteRunRequest) (*ExecuteRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteRun not implemented")
}
func (UnimplementedWeaverServiceServer) ValidateRun(context.Context, *ValidateRunRequest) (*ValidateRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRun not implemented")
}
func (UnimplementedWeaverServiceServer) InferSchema(context.Context, *InferSchemaRequest) (*InferSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InferSchema not implemented")
}
func (UnimplementedWeaverServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWeaverServiceServer) mustEmbedUnimplementedWeaverServiceServer() {}
func (UnimplementedWeaverServiceServer) testEmbeddedByValue()                       {}

// UnsafeWeaverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeaverServiceServer will
// result in compilation errors.
type UnsafeWeaverServiceServer interface {
	mustEmbedUnimplementedWeaverServiceServer()
}

func RegisterWeaverServiceServer(s grpc.ServiceRegistrar, srv WeaverServiceServer) {
	// If the following call panics, it indicates UnimplementedWeaverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeaverService_ServiceDesc, srv)
}

func _WeaverService_ExecuteRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeaverServiceServer).ExecuteRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeaverService_ExecuteRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeaverServiceServer).ExecuteRun(ctx, req.(*ExecuteRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeaverService_ValidateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeaverServiceServer).ValidateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeaverService_ValidateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeaverServiceServer).ValidateRun(ctx, req.(*ValidateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeaverService_InferSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeaverServiceServer).InferSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeaverService_InferSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeaverServiceServer).InferSchema(ctx, req.(*InferSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeaverService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeaverServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeaverService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeaverServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WeaverService_ServiceDesc is the grpc.ServiceDesc for WeaverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeaverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "texture.WeaverService",
	HandlerType: (*WeaverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteRun",
			Handler:    _WeaverService_ExecuteRun_Handler,
		},
		{
			MethodName: "ValidateRun",
			Handler:    _WeaverService_ValidateRun_Handler,
		},
		{
			MethodName: "InferSchema",
			Handler:    _WeaverService_InferSchema_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WeaverService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weaver.proto",
}
