// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: weaver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_weaver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{0}
}

// Health check response
type HealthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PythonVersion       string                 `protobuf:"bytes,2,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	AvailableAlgorithms []string               `protobuf:"bytes,3,rep,name=available_algorithms,json=availableAlgorithms,proto3" json:"available_algorithms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_weaver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *HealthResponse) GetAvailableAlgorithms() []string {
	if x != nil {
		return x.AvailableAlgorithms
	}
	return nil
}

// Execute run request
type ExecuteRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId    string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	DatasetCsv     []byte                 `protobuf:"bytes,2,opt,name=dataset_csv,json=datasetCsv,proto3" json:"dataset_csv,omitempty"` // Raw CSV data as bytes
	TargetColumn   string                 `protobuf:"bytes,3,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	FeatureColumns []string               `protobuf:"bytes,4,rep,name=feature_columns,json=featureColumns,proto3" json:"feature_columns,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestId      string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // For tracing/logging
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRunRequest) Reset() {
	*x = ExecuteRunRequest{}
	mi := &file_weaver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRunRequest) ProtoMessage() {}

func (x *ExecuteRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRunRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRunRequest) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRunRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ExecuteRunRequest) GetDatasetCsv() []byte {
	if x != nil {
		return x.DatasetCsv
	}
	return nil
}

func (x *ExecuteRunRequest) GetTargetColumn() string {
	if x != nil {
		return x.TargetColumn
	}
	return ""
}

func (x *ExecuteRunRequest) GetFeatureColumns() []string {
	if x != nil {
		return x.FeatureColumns
	}
	return nil
}

func (x *ExecuteRunRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Execute run response
type ExecuteRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // success, error
	Summary       *RunSummary            `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Charts        []*Chart               `protobuf:"bytes,4,rep,name=charts,proto3" json:"charts,omitempty"`
	Tables        []*Table               `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty"`
	Explanations  []string               `protobuf:"bytes,6,rep,name=explanations,proto3" json:"explanations,omitempty"`
	Warnings      []string               `protobuf:"bytes,7,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRunResponse) Reset() {
	*x = ExecuteRunResponse{}
	mi := &file_weaver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRunResponse) ProtoMessage() {}

func (x *ExecuteRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRunResponse.ProtoReflect.Descriptor instead.
func (*ExecuteRunResponse) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteRunResponse) GetSummary() *RunSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ExecuteRunResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ExecuteRunResponse) GetCharts() []*Chart {
	if x != nil {
		return x.Charts
	}
	return nil
}

func (x *ExecuteRunResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *ExecuteRunResponse) GetExplanations() []string {
	if x != nil {
		return x.Explanations
	}
	return nil
}

func (x *ExecuteRunResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ExecuteRunResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Run summary metadata
type RunSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetColumn   string                 `protobuf:"bytes,1,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	FeatureColumns []string               `protobuf:"bytes,2,rep,name=feature_columns,json=featureColumns,proto3" json:"feature_columns,omitempty"`
	TrainRows      int32                  `protobuf:"varint,3,opt,name=train_rows,json=trainRows,proto3" json:"train_rows,omitempty"`
	TestRows       int32                  `protobuf:"varint,4,opt,name=test_rows,json=testRows,proto3" json:"test_rows,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_weaver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{4}
}

func (x *RunSummary) GetTargetColumn() string {
	if x != nil {
		return x.TargetColumn
	}
	return ""
}

func (x *RunSummary) GetFeatureColumns() []string {
	if x != nil {
		return x.FeatureColumns
	}
	return nil
}

func (x *RunSummary) GetTrainRows() int32 {
	if x != nil {
		return x.TrainRows
	}
	return 0
}

func (x *RunSummary) GetTestRows() int32 {
	if x != nil {
		return x.TestRows
	}
	return 0
}

func (x *RunSummary) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Validate run request
type ValidateRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId    string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	ColumnNames    []string               `protobuf:"bytes,2,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
	ColumnTypes    []string               `protobuf:"bytes,3,rep,name=column_types,json=columnTypes,proto3" json:"column_types,omitempty"`
	TargetColumn   string                 `protobuf:"bytes,4,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	FeatureColumns []string               `protobuf:"bytes,5,rep,name=feature_columns,json=featureColumns,proto3" json:"feature_columns,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateRunRequest) Reset() {
	*x = ValidateRunRequest{}
	mi := &file_weaver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRunRequest) ProtoMessage() {}

func (x *ValidateRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRunRequest.ProtoReflect.Descriptor instead.
func (*ValidateRunRequest) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateRunRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ValidateRunRequest) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

func (x *ValidateRunRequest) GetColumnTypes() []string {
	if x != nil {
		return x.ColumnTypes
	}
	return nil
}

func (x *ValidateRunRequest) GetTargetColumn() string {
	if x != nil {
		return x.TargetColumn
	}
	return ""
}

func (x *ValidateRunRequest) GetFeatureColumns() []string {
	if x != nil {
		return x.FeatureColumns
	}
	return nil
}

func (x *ValidateRunRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Validate run response
type ValidateRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRunResponse) Reset() {
	*x = ValidateRunResponse{}
	mi := &file_weaver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRunResponse) ProtoMessage() {}

func (x *ValidateRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRunResponse.ProtoReflect.Descriptor instead.
func (*ValidateRunResponse) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRunResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateRunResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Infer schema request
type InferSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetCsv    []byte                 `protobuf:"bytes,1,opt,name=dataset_csv,json=datasetCsv,proto3" json:"dataset_csv,omitempty"` // Raw CSV data as bytes
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`    // Optional ID for tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferSchemaRequest) Reset() {
	*x = InferSchemaRequest{}
	mi := &file_weaver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferSchemaRequest) ProtoMessage() {}

func (x *InferSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferSchemaRequest.ProtoReflect.Descriptor instead.
func (*InferSchemaRequest) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{7}
}

func (x *InferSchemaRequest) GetDatasetCsv() []byte {
	if x != nil {
		return x.DatasetCsv
	}
	return nil
}

func (x *InferSchemaRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

// Infer schema response
type InferSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	RowCount      int32                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	ColumnCount   int32                  `protobuf:"varint,4,opt,name=column_count,json=columnCount,proto3" json:"column_count,omitempty"`
	Columns       []*ColumnSchema        `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty"`
	PreviewRows   []*PreviewRow          `protobuf:"bytes,6,rep,name=preview_rows,json=previewRows,proto3" json:"preview_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferSchemaResponse) Reset() {
	*x = InferSchemaResponse{}
	mi := &file_weaver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferSchemaResponse) ProtoMessage() {}

func (x *InferSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferSchemaResponse.ProtoReflect.Descriptor instead.
func (*InferSchemaResponse) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{8}
}

func (x *InferSchemaResponse) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *InferSchemaResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InferSchemaResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *InferSchemaResponse) GetColumnCount() int32 {
	if x != nil {
		return x.ColumnCount
	}
	return 0
}

func (x *InferSchemaResponse) GetColumns() []*ColumnSchema {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *InferSchemaResponse) GetPreviewRows() []*PreviewRow {
	if x != nil {
		return x.PreviewRows
	}
	return nil
}

// Column schema metadata
type ColumnSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InferredType  string                 `protobuf:"bytes,2,opt,name=inferred_type,json=inferredType,proto3" json:"inferred_type,omitempty"` // numeric, categorical, boolean, datetime, text, identifier
	MissingCount  int32                  `protobuf:"varint,3,opt,name=missing_count,json=missingCount,proto3" json:"missing_count,omitempty"`
	UniqueCount   int32                  `protobuf:"varint,4,opt,name=unique_count,json=uniqueCount,proto3" json:"unique_count,omitempty"`
	SampleValues  []string               `protobuf:"bytes,5,rep,name=sample_values,json=sampleValues,proto3" json:"sample_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnSchema) Reset() {
	*x = ColumnSchema{}
	mi := &file_weaver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnSchema) ProtoMessage() {}

func (x *ColumnSchema) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnSchema.ProtoReflect.Descriptor instead.
func (*ColumnSchema) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnSchema) GetInferredType() string {
	if x != nil {
		return x.InferredType
	}
	return ""
}

func (x *ColumnSchema) GetMissingCount() int32 {
	if x != nil {
		return x.MissingCount
	}
	return 0
}

func (x *ColumnSchema) GetUniqueCount() int32 {
	if x != nil {
		return x.UniqueCount
	}
	return 0
}

func (x *ColumnSchema) GetSampleValues() []string {
	if x != nil {
		return x.SampleValues
	}
	return nil
}

// Preview row (for dataset preview)
type PreviewRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         map[string]string      `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRow) Reset() {
	*x = PreviewRow{}
	mi := &file_weaver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRow) ProtoMessage() {}

func (x *PreviewRow) ProtoReflect() protoreflect.Message {
	mi := &file_weaver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRow.ProtoReflect.Descriptor instead.
func (*PreviewRow) Descriptor() ([]byte, []int) {
	return file_weaver_proto_rawDescGZIP(), []int{10}
}

func (x *PreviewRow) GetCells() map[string]string {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_weaver_proto protoreflect.FileDescriptor

const file_weaver_proto_rawDesc = "" +
	"\n" +
	"\fweaver.proto\x12\atexture\x1a\fcommon.proto\"\a\n" +
	"\x05Empty\"\x82\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0epython_version\x18\x02 \x01(\tR\rpythonVersion\x121\n" +
	"\x14available_algorithms\x18\x03 \x03(\tR\x13availableAlgorithms\"\xcf\x02\n" +
	"\x11ExecuteRunRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12\x1f\n" +
	"\vdataset_csv\x18\x02 \x01(\fR\n" +
	"datasetCsv\x12#\n" +
	"\rtarget_column\x18\x03 \x01(\tR\ftargetColumn\x12'\n" +
	"\x0ffeature_columns\x18\x04 \x03(\tR\x0efeatureColumns\x12J\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2*.texture.ExecuteRunRequest.ParametersEntryR\n" +
	"parameters\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x03\n" +
	"\x12ExecuteRunResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\asummary\x18\x02 \x01(\v2\x13.texture.RunSummaryR\asummary\x12B\n" +
	"\ametrics\x18\x03 \x03(\v2(.texture.ExecuteRunResponse.MetricsEntryR\ametrics\x12&\n" +
	"\x06charts\x18\x04 \x03(\v2\x0e.texture.ChartR\x06charts\x12&\n" +
	"\x06tables\x18\x05 \x03(\v2\x0e.texture.TableR\x06tables\x12\"\n" +
	"\fexplanations\x18\x06 \x03(\tR\fexplanations\x12\x1a\n" +
	"\bwarnings\x18\a \x03(\tR\bwarnings\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x9a\x02\n" +
	"\n" +
	"RunSummary\x12#\n" +
	"\rtarget_column\x18\x01 \x01(\tR\ftargetColumn\x12'\n" +
	"\x0ffeature_columns\x18\x02 \x03(\tR\x0efeatureColumns\x12\x1d\n" +
	"\n" +
	"train_rows\x18\x03 \x01(\x05R\ttrainRows\x12\x1b\n" +
	"\ttest_rows\x18\x04 \x01(\x05R\btestRows\x12C\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2#.texture.RunSummary.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x02\n" +
	"\x12ValidateRunRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12!\n" +
	"\fcolumn_names\x18\x02 \x03(\tR\vcolumnNames\x12!\n" +
	"\fcolumn_types\x18\x03 \x03(\tR\vcolumnTypes\x12#\n" +
	"\rtarget_column\x18\x04 \x01(\tR\ftargetColumn\x12'\n" +
	"\x0ffeature_columns\x18\x05 \x03(\tR\x0efeatureColumns\x12K\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2+.texture.ValidateRunRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13ValidateRunResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"T\n" +
	"\x12InferSchemaRequest\x12\x1f\n" +
	"\vdataset_csv\x18\x01 \x01(\fR\n" +
	"datasetCsv\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\"\xf9\x01\n" +
	"\x13InferSchemaResponse\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x05R\browCount\x12!\n" +
	"\fcolumn_count\x18\x04 \x01(\x05R\vcolumnCount\x12/\n" +
	"\acolumns\x18\x05 \x03(\v2\x15.texture.ColumnSchemaR\acolumns\x126\n" +
	"\fpreview_rows\x18\x06 \x03(\v2\x13.texture.PreviewRowR\vpreviewRows\"\xb4\x01\n" +
	"\fColumnSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rinferred_type\x18\x02 \x01(\tR\finferredType\x12#\n" +
	"\rmissing_count\x18\x03 \x01(\x05R\fmissingCount\x12!\n" +
	"\funique_count\x18\x04 \x01(\x05R\vuniqueCount\x12#\n" +
	"\rsample_values\x18\x05 \x03(\tR\fsampleValues\"|\n" +
	"\n" +
	"PreviewRow\x124\n" +
	"\x05cells\x18\x01 \x03(\v2\x1e.texture.PreviewRow.CellsEntryR\x05cells\x1a8\n" +
	"\n" +
	"CellsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa2\x02\n" +
	"\rWeaverService\x12E\n" +
	"\n" +
	"ExecuteRun\x12\x1a.texture.ExecuteRunRequest\x1a\x1b.texture.ExecuteRunResponse\x12H\n" +
	"\vValidateRun\x12\x1b.texture.ValidateRunRequest\x1a\x1c.texture.ValidateRunResponse\x12H\n" +
	"\vInferSchema\x12\x1b.texture.InferSchemaRequest\x1a\x1c.texture.InferSchemaResponse\x126\n" +
	"\vHealthCheck\x12\x0e.texture.Empty\x1a\x17.texture.HealthResponseB\"Z github.com/sadhasivam/texture/pbb\x06proto3"

var (
	file_weaver_proto_rawDescOnce sync.Once
	file_weaver_proto_rawDescData []byte
)

func file_weaver_proto_rawDescGZIP() []byte {
	file_weaver_proto_rawDescOnce.Do(func() {
		file_weaver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weaver_proto_rawDesc), len(file_weaver_proto_rawDesc)))
	})
	return file_weaver_proto_rawDescData
}

var file_weaver_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_weaver_proto_goTypes = []any{
	(*Empty)(nil),               // 0: texture.Empty
	(*HealthResponse)(nil),      // 1: texture.HealthResponse
	(*ExecuteRunRequest)(nil),   // 2: texture.ExecuteRunRequest
	(*ExecuteRunResponse)(nil),  // 3: texture.ExecuteRunResponse
	(*RunSummary)(nil),          // 4: texture.RunSummary
	(*ValidateRunRequest)(nil),  // 5: texture.ValidateRunRequest
	(*ValidateRunResponse)(nil), // 6: texture.ValidateRunResponse
	(*InferSchemaRequest)(nil),  // 7: texture.InferSchemaRequest
	(*InferSchemaResponse)(nil), // 8: texture.InferSchemaResponse
	(*ColumnSchema)(nil),        // 9: texture.ColumnSchema
	(*PreviewRow)(nil),          // 10: texture.PreviewRow
	nil,                         // 11: texture.ExecuteRunRequest.ParametersEntry
	nil,                         // 12: texture.ExecuteRunResponse.MetricsEntry
	nil,                         // 13: texture.RunSummary.ParametersEntry
	nil,                         // 14: texture.ValidateRunRequest.ParametersEntry
	nil,                         // 15: texture.PreviewRow.CellsEntry
	(*Chart)(nil),               // 16: texture.Chart
	(*Table)(nil),               // 17: texture.Table
}
var file_weaver_proto_depIdxs = []int32{
	11, // 0: texture.ExecuteRunRequest.parameters:type_name -> texture.ExecuteRunRequest.ParametersEntry
	4,  // 1: texture.ExecuteRunResponse.summary:type_name -> texture.RunSummary
	12, // 2: texture.ExecuteRunResponse.metrics:type_name -> texture.ExecuteRunResponse.MetricsEntry
	16, // 3: texture.ExecuteRunResponse.charts:type_name -> texture.Chart
	17, // 4: texture.ExecuteRunResponse.tables:type_name -> texture.Table
	13, // 5: texture.RunSummary.parameters:type_name -> texture.RunSummary.ParametersEntry
	14, // 6: texture.ValidateRunRequest.parameters:type_name -> texture.ValidateRunRequest.ParametersEntry
	9,  // 7: texture.InferSchemaResponse.columns:type_name -> texture.ColumnSchema
	10, // 8: texture.InferSchemaResponse.preview_rows:type_name -> texture.PreviewRow
	15, // 9: texture.PreviewRow.cells:type_name -> texture.PreviewRow.CellsEntry
	2,  // 10: texture.WeaverService.ExecuteRun:input_type -> texture.ExecuteRunRequest
	5,  // 11: texture.WeaverService.ValidateRun:input_type -> texture.ValidateRunRequest
	7,  // 12: texture.WeaverService.InferSchema:input_type -> texture.InferSchemaRequest
	0,  // 13: texture.WeaverService.HealthCheck:input_type -> texture.Empty
	3,  // 14: texture.WeaverService.ExecuteRun:output_type -> texture.ExecuteRunResponse
	6,  // 15: texture.WeaverService.ValidateRun:output_type -> texture.ValidateRunResponse
	8,  // 16: texture.WeaverService.InferSchema:output_type -> texture.InferSchemaResponse
	1,  // 17: texture.WeaverService.HealthCheck:output_type -> texture.HealthResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_weaver_proto_init() }
func file_weaver_proto_init() {
	if File_weaver_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weaver_proto_rawDesc), len(file_weaver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weaver_proto_goTypes,
		DependencyIndexes: file_weaver_proto_depIdxs,
		MessageInfos:      file_weaver_proto_msgTypes,
	}.Build()
	File_weaver_proto = out.File
	file_weaver_proto_goTypes = nil
	file_weaver_proto_depIdxs = nil
}
