# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63ommon.proto\x12\x07texture"\xa4\x01\n\x05\x43hart\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12 \n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x12.texture.DataPoint\x12,\n\x07options\x18\x04 \x03(\x0b\x32\x1b.texture.Chart.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"j\n\tDataPoint\x12.\n\x06values\x18\x01 \x03(\x0b\x32\x1e.texture.DataPoint.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01"B\n\x05Table\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x03(\t\x12\x1a\n\x04rows\x18\x03 \x03(\x0b\x32\x0c.texture.Row"[\n\x03Row\x12&\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\x17.texture.Row.CellsEntry\x1a,\n\nCellsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42"Z github.com/sadhasivam/texture/pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z github.com/sadhasivam/texture/pb"
    _globals["_CHART_OPTIONSENTRY"]._loaded_options = None
    _globals["_CHART_OPTIONSENTRY"]._serialized_options = b"8\001"
    _globals["_DATAPOINT_VALUESENTRY"]._loaded_options = None
    _globals["_DATAPOINT_VALUESENTRY"]._serialized_options = b"8\001"
    _globals["_ROW_CELLSENTRY"]._loaded_options = None
    _globals["_ROW_CELLSENTRY"]._serialized_options = b"8\001"
    _globals["_CHART"]._serialized_start = 26
    _globals["_CHART"]._serialized_end = 190
    _globals["_CHART_OPTIONSENTRY"]._serialized_start = 144
    _globals["_CHART_OPTIONSENTRY"]._serialized_end = 190
    _globals["_DATAPOINT"]._serialized_start = 192
    _globals["_DATAPOINT"]._serialized_end = 298
    _globals["_DATAPOINT_VALUESENTRY"]._serialized_start = 253
    _globals["_DATAPOINT_VALUESENTRY"]._serialized_end = 298
    _globals["_TABLE"]._serialized_start = 300
    _globals["_TABLE"]._serialized_end = 366
    _globals["_ROW"]._serialized_start = 368
    _globals["_ROW"]._serialized_end = 459
    _globals["_ROW_CELLSENTRY"]._serialized_start = 415
    _globals["_ROW_CELLSENTRY"]._serialized_end = 459
# @@protoc_insertion_point(module_scope)
