# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import weaver_pb2 as weaver__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in weaver_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WeaverServiceStub:
    """Weaver service - ML computation engine"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteRun = channel.unary_unary(
            "/texture.WeaverService/ExecuteRun",
            request_serializer=weaver__pb2.ExecuteRunRequest.SerializeToString,
            response_deserializer=weaver__pb2.ExecuteRunResponse.FromString,
            _registered_method=True,
        )
        self.ValidateRun = channel.unary_unary(
            "/texture.WeaverService/ValidateRun",
            request_serializer=weaver__pb2.ValidateRunRequest.SerializeToString,
            response_deserializer=weaver__pb2.ValidateRunResponse.FromString,
            _registered_method=True,
        )
        self.InferSchema = channel.unary_unary(
            "/texture.WeaverService/InferSchema",
            request_serializer=weaver__pb2.InferSchemaRequest.SerializeToString,
            response_deserializer=weaver__pb2.InferSchemaResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/texture.WeaverService/HealthCheck",
            request_serializer=weaver__pb2.Empty.SerializeToString,
            response_deserializer=weaver__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class WeaverServiceServicer:
    """Weaver service - ML computation engine"""

    def ExecuteRun(self, request, context):
        """Execute an algorithm run"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateRun(self, request, context):
        """Validate if a run can be executed"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InferSchema(self, request, context):
        """Infer schema from CSV data"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WeaverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteRun": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteRun,
            request_deserializer=weaver__pb2.ExecuteRunRequest.FromString,
            response_serializer=weaver__pb2.ExecuteRunResponse.SerializeToString,
        ),
        "ValidateRun": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateRun,
            request_deserializer=weaver__pb2.ValidateRunRequest.FromString,
            response_serializer=weaver__pb2.ValidateRunResponse.SerializeToString,
        ),
        "InferSchema": grpc.unary_unary_rpc_method_handler(
            servicer.InferSchema,
            request_deserializer=weaver__pb2.InferSchemaRequest.FromString,
            response_serializer=weaver__pb2.InferSchemaResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=weaver__pb2.Empty.FromString,
            response_serializer=weaver__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "texture.WeaverService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("texture.WeaverService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class WeaverService:
    """Weaver service - ML computation engine"""

    @staticmethod
    def ExecuteRun(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/texture.WeaverService/ExecuteRun",
            weaver__pb2.ExecuteRunRequest.SerializeToString,
            weaver__pb2.ExecuteRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateRun(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/texture.WeaverService/ValidateRun",
            weaver__pb2.ValidateRunRequest.SerializeToString,
            weaver__pb2.ValidateRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InferSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/texture.WeaverService/InferSchema",
            weaver__pb2.InferSchemaRequest.SerializeToString,
            weaver__pb2.InferSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/texture.WeaverService/HealthCheck",
            weaver__pb2.Empty.SerializeToString,
            weaver__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
